feat: transcation success
ping-pub/widget pull request #11
Opened 2024-03-29 13:34 UTC by showzyl

2024-03-31 12:17 UTC, liangping requested changes

2024-03-31 12:17 UTC, liangping commented on lib/components/TokenConvert/index.vue
> +            sequence: acc.account.sequence,
Why do you change these line?

2024-03-31 12:17 UTC, liangping commented on lib/components/TokenConvert/tokens.ts
> +    },
Please remove this config here.

2024-03-31 12:17 UTC, liangping commented on lib/components/TxDialog/index.vue
> +const chainId = ref('taproot-1');
please use `comsoshub-4` as default chain-id

2024-03-31 12:17 UTC, liangping commented on lib/components/TxDialog/messages/Send.vue
> +    console.log(`props: `, props);
remove console.

2024-03-31 12:17 UTC, liangping commented on lib/wallet/UniClient.ts
> +        console.log(`transaction: `, transaction);
remove console

2024-04-01 01:32 UTC, showzyl commented on lib/components/TokenConvert/index.vue
> +            sequence: acc.account.sequence,
i remove Number and add this line

2024-04-03 00:34 UTC, merged